name: epi
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - intel-openmp=2025.0.0
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - ncurses=6.5
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.0.18
  - pip=25.2
  - pthread-stubs=0.3
  - python=3.11.13
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.50.2
  - tbb=2022.0.0
  - tbb-devel=2022.0.0
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - accelerate==0.18.0
      - adjusttext==1.3.0
      - agilerl==2.0.6
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bleach==6.2.0
      - cachetools==6.2.1
      - certifi==2025.10.5
      - cffi==2.0.0
      - cfgv==3.4.0
      - charset-normalizer==3.4.4
      - click==8.3.0
      - cloudpickle==3.1.1
      - comm==0.2.3
      - contourpy==1.3.3
      - cycler==0.12.1
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - dill==0.3.9
      - distlib==0.4.0
      - docker-pycreds==0.4.0
      - et-xmlfile==2.0.0
      - executing==2.2.1
      - farama-notifications==0.0.4
      - fastjsonschema==2.21.2
      - fastrand==1.8.0
      - ffmpeg==1.4
      - filelock==3.20.0
      - flatten-dict==0.4.2
      - fonttools==4.60.1
      - fqdn==1.5.1
      - fsspec==2025.9.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-api-core==2.26.0
      - google-auth==2.41.1
      - google-cloud-core==2.4.3
      - google-cloud-storage==2.19.0
      - google-crc32c==1.7.1
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.70.0
      - gymnasium==0.29.1
      - h11==0.16.0
      - h5py==3.15.1
      - hf-xet==1.1.10
      - highlight-text==0.2
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.35.3
      - hydra-core==1.3.2
      - identify==2.6.15
      - idna==3.11
      - ipykernel==7.0.1
      - ipython==9.6.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - jax==0.4.38
      - jaxlib==0.4.38
      - jedi==0.19.2
      - jinja2==3.1.6
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.9
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.9
      - lark==1.3.0
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.9.4
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - minari==0.5.3
      - mistune==3.1.4
      - ml-dtypes==0.5.3
      - mpmath==1.3.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.5
      - nodeenv==1.9.1
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - orjson==3.11.3
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pettingzoo==1.24.3
      - pexpect==4.9.0
      - pillow==12.0.0
      - platformdirs==4.5.0
      - pre-commit==3.8.0
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - psutil==7.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pygame==2.6.1
      - pygments==2.19.2
      - pymunk==6.11.1
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - python-json-logger==4.0.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - redis==4.6.0
      - referencing==0.37.0
      - regex==2025.9.18
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.2.0
      - rpds-py==0.27.1
      - rsa==4.9.1
      - safetensors==0.6.2
      - scipy==1.16.2
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentry-sdk==2.42.0
      - setproctitle==1.3.7
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - stack-data==0.6.3
      - supersuit==3.9.3
      - sympy==1.13.1
      - tensordict==0.6.2
      - termcolor==1.1.0
      - terminado==0.18.1
      - tinycss2==1.4.0
      - tinyscaler==1.2.8
      - tokenizers==0.22.1
      - torch==2.5.1
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.57.1
      - triton==3.1.0
      - typer==0.19.2
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - ucimlrepo==0.0.3
      - uri-template==1.3.0
      - urllib3==2.5.0
      - virtualenv==20.35.3
      - wandb==0.17.9
      - wcwidth==0.2.14
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - widgetsnbextension==4.0.14
prefix: /home/duke1213/miniconda3/envs/epi
